#!/usr/bin/env python3
"""
One-command Squarespace paste pipeline: rebuild the paste-ready payload for
any page in this repo and put it on the clipboard.

Usage:
  python3 scripts/squarespace.py                    list every known target
  python3 scripts/squarespace.py our-team           rebuild + copy to clipboard
  python3 scripts/squarespace.py snap-medicaid-timeline
  python3 scripts/squarespace.py tax-timeline       any dir/page works (generic)
  python3 scripts/squarespace.py --all              rebuild everything, no copy
  python3 scripts/squarespace.py our-team --no-copy rebuild only

Target resolution (first match wins):

  1. A page built by build_squarespace.py (any MARKER_PAGES stem, plus
     index/home, support, ufsm)  ->  re-run the builder suite, copy
     squarespace-ready/<name>.html.
  2. A hand-authored snippet with no build source (squarespace-header-search,
     squarespace-footer, squarespace-code-injection, video-hero)  ->  copy the
     file as-is.
  3. Anything else — a directory containing index.html, or any .html path —
     ->  GENERIC embed builder (below)  ->  <dir>/squarespace-inject.html,
     then copy.

The generic builder is what makes new pages cheap. It reuses
build_squarespace.py's shared passes (absolutize_assets, remap_internal_links,
ensure_okina, entity_encode, scope_css_selectors) and handles both authoring
styles found in this repo:

  * embed-ready — the <body> holds a single wrapper <div id="…"> (e.g.
    snap-medicaid-timeline). The wrapper block is lifted out unchanged; its
    CSS is trusted to be self-scoped.
  * standalone — a normal full page (e.g. tax-timeline). The head <style>
    blocks and body content are wrapped in <div id="ha-<slug>-embed">, every
    CSS selector is auto-scoped under that id, and the standard mobile
    full-bleed breakout is appended.

Either way, load-time init is made injection-safe: in the Squarespace editor
the block is inserted after the page's load event has already fired, so a
plain `window.onload = fn` or 'load'/'DOMContentLoaded' listener would never
run. Those are rewritten to readyState-guarded forms (the same fix the
original hand-patched snap-medicaid-timeline inject used).
"""
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_squarespace as bs

ROOT = bs.ROOT


# ---------------------------------------------------------------------------
# Injection-safe load-time init
# ---------------------------------------------------------------------------

ONLOAD_HELPER = (
    '<script>\n'
    "/* Squarespace-fit: in the editor this block is injected AFTER the page's\n"
    "   load event, so 'load'/'DOMContentLoaded' listeners registered here\n"
    "   would never fire. Run the callback immediately when the moment has\n"
    "   already passed. (Generated by scripts/squarespace.py.) */\n"
    "function __haOnLoad(f){document.readyState==='complete'"
    "?setTimeout(f,0):window.addEventListener('load',f);}\n"
    "function __haOnReady(f){document.readyState!=='loading'"
    "?setTimeout(f,0):document.addEventListener('DOMContentLoaded',f);}\n"
    '</script>'
)


def _expr_end(js, start):
    """Index just past the `;` terminating the expression starting at
    `start`, tracking bracket depth and string/template literals so arrow
    functions with bodies scan correctly."""
    depth = 0
    i = start
    n = len(js)
    while i < n:
        c = js[i]
        if c in "'\"`":
            q = c
            i += 1
            while i < n and js[i] != q:
                i += 2 if js[i] == "\\" else 1
            i += 1
            continue
        if c in "({[":
            depth += 1
        elif c in ")}]":
            depth -= 1
        elif c == ";" and depth <= 0:
            return i + 1
        i += 1
    return n


def patch_onload(html):
    """Rewrite load-time init so it still runs when injected post-load.
    Returns (html, patched?)."""
    patched = False

    # window.onload = <expr>;  ->  guarded named init
    out, i, k = [], 0, 0
    while True:
        m = re.search(r"window\.onload\s*=\s*", html[i:])
        if not m:
            out.append(html[i:])
            break
        expr_start = i + m.end()
        end = _expr_end(html, expr_start)
        expr = html[expr_start:end].rstrip().rstrip(";")
        name = "__haInit%d" % k
        out.append(html[i:i + m.start()])
        out.append(
            "var %s = %s;\n"
            "        if (document.readyState === 'complete') "
            "{ setTimeout(%s, 0); }\n"
            "        else { window.addEventListener('load', %s); }"
            % (name, expr, name, name)
        )
        i, k, patched = end, k + 1, True
    html = "".join(out)

    # addEventListener forms: replacing the call head leaves `fn)` behind,
    # which closes the helper call exactly. (A rare third options arg would
    # ride along as an ignored extra parameter — harmless.)
    for pat, repl in (
        (r"window\.addEventListener\(\s*['\"]load['\"]\s*,\s*", "__haOnLoad("),
        (r"document\.addEventListener\(\s*['\"]DOMContentLoaded['\"]\s*,\s*",
         "__haOnReady("),
    ):
        html, n = re.subn(pat, repl, html)
        patched = patched or bool(n)

    return html, patched


# ---------------------------------------------------------------------------
# Generic embed builder
# ---------------------------------------------------------------------------

def _slug(rel_html):
    d = os.path.dirname(rel_html)
    return (d or os.path.splitext(os.path.basename(rel_html))[0]).replace("/", "-")


def _normalize_updirs(html, rel_html):
    """A page one directory deep references shared files as ../assets/… and
    ../support.html. Rewrite to root-relative so build_squarespace's shared
    passes (which expect root-page paths) can absolutize/remap them."""
    if os.path.dirname(rel_html):
        html = html.replace('"../assets/', '"assets/')
        html = html.replace("'../assets/", "'assets/")
        html = html.replace("(../assets/", "(assets/")
        html = re.sub(r'href="\.\./([^/"][^"]*)"', r'href="\1"', html)
    return html


def build_generic(rel_html):
    """Build a paste-ready injection from any standalone HTML page."""
    lines = bs.read(rel_html)
    body_i = bs._find(lines, "<body")
    body_close = bs._find(lines, "</body>")
    body = [l for l in lines[body_i + 1:body_close]]
    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()

    # Head pieces: font links + <style> blocks (meta/title are dropped;
    # local stylesheet links other than okina.css are kept and later
    # absolutized to the Pages host by the shared passes).
    head = lines[:body_i]
    fonts = [l for l in head
             if "fonts.googleapis" in l or "fonts.gstatic" in l]
    links = [l.strip() for l in head
             if re.search(r'<link[^>]*rel="stylesheet"', l)
             and "okina.css" not in l
             and "fonts.googleapis" not in l]
    styles = []
    j = 0
    while j < len(head):
        if "<style" in head[j]:
            k = j
            while "</style>" not in head[k]:
                k += 1
            styles.append("\n".join(head[j:k + 1]))
            j = k + 1
        else:
            j += 1

    wrapper_m = re.match(r'\s*<div id="([^"]+)"\s*>\s*$', body[0]) if body else None
    embed_ready = bool(wrapper_m) and body[-1].strip() == "</div>"

    if embed_ready:
        wrapper = wrapper_m.group(1)
        note = ("embed-ready page — its own <div id=\"%s\"> wrapper block is "
                "used verbatim (CSS is trusted to be self-scoped); load-time "
                "init rewritten to survive post-load injection" % wrapper)
        parts = fonts + links + styles + body
        content = "\n".join(parts)
    else:
        wrapper = "ha-%s-embed" % _slug(rel_html)
        css = "\n".join(
            re.sub(r"(?s)^\s*<style[^>]*>|</style>\s*$", "", s) for s in styles
        )
        # The two universal resets used across this codebase must keep zero
        # specificity — same :where() treatment as build_homepage()/support().
        css = css.replace(
            "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }",
            ":where(#%s, #%s *, #%s *::before, #%s *::after) "
            "{ box-sizing: border-box; margin: 0; padding: 0; }"
            % (wrapper, wrapper, wrapper, wrapper),
        )
        css = css.replace(
            "*, *::before, *::after{",
            ":where(#%s *, #%s *::before, #%s *::after){" % (wrapper, wrapper, wrapper),
        )
        css = re.sub(r"(?m)^(\s*)html\s*\{[^}]*\}", "", css)
        css = re.sub(r"(?m)^(\s*)body\s*\{", r"\1#%s {" % wrapper, css, count=1)
        css = "<style>\n" + bs.scope_css_selectors(css, wrapper) + "\n</style>"
        # Standard mobile full-bleed breakout (Squarespace pads the code
        # block's content column on mobile) — same fix as every other page.
        css += (
            "\n<style>\n"
            "@media (max-width:1080px){\n"
            "  #%s{\n"
            "    width: 100vw !important;\n"
            "    max-width: 100vw !important;\n"
            "    margin-left: calc(50%% - 50vw) !important;\n"
            "    margin-right: calc(50%% - 50vw) !important;\n"
            "  }\n"
            "}\n"
            "</style>\n" % wrapper
        )
        note = ("standalone page auto-scoped under #%s by the generic builder "
                "(scripts/squarespace.py); load-time init rewritten to survive "
                "post-load injection" % wrapper)
        content = (
            '<div id="%s">\n' % wrapper
            + "\n".join(fonts + links) + "\n"
            + css + "\n"
            + "\n".join(body) + "\n"
            + "</div>"
        )

    content, patched = patch_onload(content)
    if patched:
        # The helper must precede the content scripts that call it.
        content = re.sub(r'(<div id="[^"]+"\s*>)',
                         lambda m: m.group(1) + "\n" + ONLOAD_HELPER,
                         content, count=1)

    page_name = _slug(rel_html)
    html = (bs.header(page_name, note)
            .replace("scripts/build_squarespace.py", "scripts/squarespace.py")
            + content + "\n")
    html = _normalize_updirs(html, rel_html)
    html = bs.entity_encode(bs.ensure_okina(bs.remap_internal_links(
        bs.absolutize_assets(html))))

    if os.path.basename(rel_html) == "index.html" and os.path.dirname(rel_html):
        out_rel = os.path.join(os.path.dirname(rel_html), "squarespace-inject.html")
    elif os.path.dirname(rel_html):
        out_rel = os.path.join(
            os.path.dirname(rel_html),
            os.path.splitext(os.path.basename(rel_html))[0] + ".squarespace-inject.html")
    else:
        out_rel = os.path.splitext(rel_html)[0] + ".squarespace-inject.html"
    out_path = os.path.join(ROOT, out_rel)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return out_rel


# ---------------------------------------------------------------------------
# Target resolution
# ---------------------------------------------------------------------------

# Hand-authored snippets: no build source, copy as-is.
SNIPPETS = {
    "header-search": "squarespace-header-search.html",
    "footer": "squarespace-footer.html",
    "code-injection": "squarespace-code-injection.html",
    "custom-css": "squarespace-custom-css.css",
    "video-hero": "video-hero/squarespace-inject.html",
}


def builder_targets():
    """name -> squarespace-ready output file, for every build_squarespace page."""
    t = {os.path.splitext(src)[0]: src for src, _, _, _ in bs.MARKER_PAGES}
    t.update({"index": "index.html", "home": "index.html",
              "support": "support.html", "ufsm": "ufsm.html"})
    return t


def generic_sources():
    """Existing generic injects that have a rebuildable source next to them."""
    found = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames
                       if d not in (".git", "node_modules", "squarespace-ready")]
        if "squarespace-inject.html" in filenames and "index.html" in filenames:
            found.append(os.path.relpath(os.path.join(dirpath, "index.html"), ROOT))
    return sorted(found)


def pbcopy(path):
    with open(path, "rb") as f:
        data = f.read()
    subprocess.run(["pbcopy"], input=data, check=True)
    return len(data)


# ---------------------------------------------------------------------------
# --snippet: browser-console paste (see README "Pasting from the browser")
# ---------------------------------------------------------------------------

# One self-contained expression, pasted into the DevTools console (or run by
# Claude via the Chrome MCP) while a Code Block editor is open. It pulls the
# payload straight from GitHub Pages, so the bytes never travel through the
# clipboard or a chat transcript, and size is irrelevant.
#
# Why it is built this way (all four verified live in the 7.1 editor):
#   • Squarespace's code editor is CodeMirror 6 and exposes no EditorView on
#     the DOM, so the document is replaced through the two events CM6 itself
#     listens for: a synthetic Mod-A keydown (its keymap runs selectAll on the
#     STATE, which a DOM Selection cannot do — CM6 only renders the visible
#     lines) followed by a synthetic paste carrying a DataTransfer.
#   • A synthetic paste does register with Squarespace's change tracking: the
#     SAVE button lights up, so the edit is real and will persist.
#   • A real Cmd+V does NOT work — the automation layer's key events do not
#     drive a native clipboard paste.
#   • navigator.clipboard.readText() is a dead end: it needs a focused tab AND
#     a one-time permission grant, and hangs the tab while that prompt is up.
SNIPPET_JS = (
    "await (async () => {"
    "const t = await fetch('%s?t=' + Date.now(), {cache:'no-store'})"
    ".then(r => r.ok ? r.text() : Promise.reject('HTTP ' + r.status));"
    "const c = document.querySelector('.cm-content');"
    "if (!c) throw new Error('No code editor found - open the Code Block editor first');"
    "c.focus();"
    "c.dispatchEvent(new KeyboardEvent('keydown',{key:'a',code:'KeyA',metaKey:true,"
    "keyCode:65,which:65,bubbles:true,cancelable:true}));"
    "const d = new DataTransfer(); d.setData('text/plain', t);"
    "c.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));"
    "return 'pasted ' + t.length + ' chars';})()"
)


def pages_url(rel_out):
    return bs.ASSET_BASE + rel_out.replace(os.sep, "/")


def check_pages_matches(rel_out):
    """True if GitHub Pages already serves the local bytes. The snippet reads
    from Pages, so an unpushed payload would silently paste the OLD content —
    exactly the stale-paste failure this pipeline exists to prevent."""
    import hashlib
    import urllib.request
    local = hashlib.sha256(open(os.path.join(ROOT, rel_out), "rb").read()).hexdigest()
    try:
        with urllib.request.urlopen(pages_url(rel_out) + "?t=check", timeout=20) as r:
            remote = hashlib.sha256(r.read()).hexdigest()
    except Exception as e:
        return None, "could not reach GitHub Pages (%s)" % e
    return local == remote, None


def emit_snippet(rel_out):
    url = pages_url(rel_out)
    match, err = check_pages_matches(rel_out)
    if err:
        print("WARNING: %s — snippet may paste stale content." % err)
    elif not match:
        print("WARNING: GitHub Pages is serving DIFFERENT bytes than your local")
        print("         %s" % rel_out)
        print("         Commit + push and wait for the Pages deploy (~90s), else")
        print("         this snippet pastes the OLD payload. Re-run to re-check.")
    else:
        print("GitHub Pages is serving the current bytes. ✓")
    js = SNIPPET_JS % url
    subprocess.run(["pbcopy"], input=js.encode("utf-8"), check=True)
    print("\nConsole snippet is on the clipboard (%d chars). Source:\n  %s" % (len(js), url))
    print("\nHow to use:")
    print("  1. Squarespace > the page > EDIT > double-click the Code Block")
    print("     (its editor panel opens on the right; leave Display Source OFF)")
    print("  2. Open DevTools (Cmd+Opt+I) > Console > paste the snippet > Enter")
    print("     It prints  'pasted N chars'  and the SAVE button lights up.")
    print("  3. Check the payload, then click SAVE yourself.")
    print("\nNote: embedded scripts stay disabled while you are logged in and")
    print("editing, so the block shows a placeholder until you preview or log out.")
    print("\n" + js)


def copy_and_report(rel_out):
    size = pbcopy(os.path.join(ROOT, rel_out))
    print("\n%s (%d KB) is on the clipboard." % (rel_out, round(size / 1024)))
    print("Squarespace: Edit page > add/select Code Block > select all > paste"
          " > Display Source OFF > Save.")


def list_targets():
    print("Built by build_squarespace.py (squarespace-ready/):")
    for name in sorted(set(builder_targets()) - {"home"}):
        print("  %s" % name)
    print("Generic injects (rebuilt from <dir>/index.html):")
    for src in generic_sources():
        print("  %s" % os.path.dirname(src))
    print("Hand-authored snippets (copied as-is):")
    for name, path in sorted(SNIPPETS.items()):
        print("  %-14s -> %s" % (name, path))
    print("Anything else: pass a directory with index.html, or any .html path.")


def main(argv):
    snippet = "--snippet" in argv
    copy = "--no-copy" not in argv and not snippet
    argv = [a for a in argv if a not in ("--no-copy", "--snippet")]

    if not argv:
        list_targets()
        return 0

    if argv[0] == "--all":
        bs.main()
        for src in generic_sources():
            print("regenerated %s" % build_generic(src))
        return 0

    target = argv[0].rstrip("/")

    known = builder_targets()
    stem = os.path.splitext(target)[0]
    if stem in known:
        bs.main()
        out = os.path.join("squarespace-ready", known[stem])
    elif target in SNIPPETS:
        out = SNIPPETS[target]
    else:
        # Generic: directory with index.html, or a direct .html path.
        if os.path.isdir(os.path.join(ROOT, target)):
            rel = os.path.join(target, "index.html")
        else:
            rel = target if target.endswith(".html") else target + ".html"
        if not os.path.exists(os.path.join(ROOT, rel)):
            print("No such target: %s (run with no arguments to list)" % target,
                  file=sys.stderr)
            return 1
        out = build_generic(rel)
        print("built %s" % out)

    if snippet:
        emit_snippet(out)
    elif copy:
        copy_and_report(out)
    else:
        print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
