#!/usr/bin/env python3
"""
One-command Squarespace paste pipeline: rebuild the paste-ready payload for
any page in this repo and put it on the clipboard.

Usage:
  python3 scripts/squarespace.py                    list every known target
  python3 scripts/squarespace.py our-team           rebuild + copy to clipboard
  python3 scripts/squarespace.py snap-medicaid-timeline
  python3 scripts/squarespace.py tax-timeline       any dir/page works (generic)
  python3 scripts/squarespace.py --all              rebuild everything, no copy
  python3 scripts/squarespace.py our-team --no-copy rebuild only
  python3 scripts/squarespace.py --status           which live pages have drifted
  python3 scripts/squarespace.py our-team --status  just that one
  python3 scripts/squarespace.py our-team --go      rebuild + push + wait for
                                                    Pages + self-driving snippet
                                                    on the clipboard + open the
                                                    Squarespace editor in Chrome

Target resolution (first match wins):

  1. A page built by build_squarespace.py (any MARKER_PAGES stem, plus
     index/home, support, ufsm)  ->  re-run the builder suite, copy
     squarespace-ready/<name>.html.
  2. A hand-authored snippet with no build source (squarespace-header-search,
     squarespace-footer, squarespace-code-injection, video-hero)  ->  copy the
     file as-is.
  3. Anything else — a directory containing index.html, or any .html path —
     ->  GENERIC embed builder (below)  ->  <dir>/squarespace-inject.html,
     then copy.

The generic builder is what makes new pages cheap. It reuses
build_squarespace.py's shared passes (absolutize_assets, remap_internal_links,
ensure_okina, entity_encode, scope_css_selectors) and handles both authoring
styles found in this repo:

  * embed-ready — the <body> holds a single wrapper <div id="…"> (e.g.
    snap-medicaid-timeline). The wrapper block is lifted out unchanged; its
    CSS is trusted to be self-scoped.
  * standalone — a normal full page (e.g. tax-timeline). The head <style>
    blocks and body content are wrapped in <div id="ha-<slug>-embed">, every
    CSS selector is auto-scoped under that id, and the standard mobile
    full-bleed breakout is appended.

Either way, load-time init is made injection-safe: in the Squarespace editor
the block is inserted after the page's load event has already fired, so a
plain `window.onload = fn` or 'load'/'DOMContentLoaded' listener would never
run. Those are rewritten to readyState-guarded forms (the same fix the
original hand-patched snap-medicaid-timeline inject used).
"""
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_squarespace as bs

ROOT = bs.ROOT


# ---------------------------------------------------------------------------
# Injection-safe load-time init
# ---------------------------------------------------------------------------

ONLOAD_HELPER = (
    '<script>\n'
    "/* Squarespace-fit: in the editor this block is injected AFTER the page's\n"
    "   load event, so 'load'/'DOMContentLoaded' listeners registered here\n"
    "   would never fire. Run the callback immediately when the moment has\n"
    "   already passed. (Generated by scripts/squarespace.py.) */\n"
    "function __haOnLoad(f){document.readyState==='complete'"
    "?setTimeout(f,0):window.addEventListener('load',f);}\n"
    "function __haOnReady(f){document.readyState!=='loading'"
    "?setTimeout(f,0):document.addEventListener('DOMContentLoaded',f);}\n"
    '</script>'
)


def _expr_end(js, start):
    """Index just past the `;` terminating the expression starting at
    `start`, tracking bracket depth and string/template literals so arrow
    functions with bodies scan correctly."""
    depth = 0
    i = start
    n = len(js)
    while i < n:
        c = js[i]
        if c in "'\"`":
            q = c
            i += 1
            while i < n and js[i] != q:
                i += 2 if js[i] == "\\" else 1
            i += 1
            continue
        if c in "({[":
            depth += 1
        elif c in ")}]":
            depth -= 1
        elif c == ";" and depth <= 0:
            return i + 1
        i += 1
    return n


def patch_onload(html):
    """Rewrite load-time init so it still runs when injected post-load.
    Returns (html, patched?)."""
    patched = False

    # window.onload = <expr>;  ->  guarded named init
    out, i, k = [], 0, 0
    while True:
        m = re.search(r"window\.onload\s*=\s*", html[i:])
        if not m:
            out.append(html[i:])
            break
        expr_start = i + m.end()
        end = _expr_end(html, expr_start)
        expr = html[expr_start:end].rstrip().rstrip(";")
        name = "__haInit%d" % k
        out.append(html[i:i + m.start()])
        out.append(
            "var %s = %s;\n"
            "        if (document.readyState === 'complete') "
            "{ setTimeout(%s, 0); }\n"
            "        else { window.addEventListener('load', %s); }"
            % (name, expr, name, name)
        )
        i, k, patched = end, k + 1, True
    html = "".join(out)

    # addEventListener forms: replacing the call head leaves `fn)` behind,
    # which closes the helper call exactly. (A rare third options arg would
    # ride along as an ignored extra parameter — harmless.)
    for pat, repl in (
        (r"window\.addEventListener\(\s*['\"]load['\"]\s*,\s*", "__haOnLoad("),
        (r"document\.addEventListener\(\s*['\"]DOMContentLoaded['\"]\s*,\s*",
         "__haOnReady("),
    ):
        html, n = re.subn(pat, repl, html)
        patched = patched or bool(n)

    return html, patched


# ---------------------------------------------------------------------------
# Generic embed builder
# ---------------------------------------------------------------------------

def _slug(rel_html):
    d = os.path.dirname(rel_html)
    return (d or os.path.splitext(os.path.basename(rel_html))[0]).replace("/", "-")


def _normalize_updirs(html, rel_html):
    """A page one directory deep references shared files as ../assets/… and
    ../support.html. Rewrite to root-relative so build_squarespace's shared
    passes (which expect root-page paths) can absolutize/remap them."""
    if os.path.dirname(rel_html):
        html = html.replace('"../assets/', '"assets/')
        html = html.replace("'../assets/", "'assets/")
        html = html.replace("(../assets/", "(assets/")
        html = re.sub(r'href="\.\./([^/"][^"]*)"', r'href="\1"', html)
    return html


def build_generic(rel_html):
    """Build a paste-ready injection from any standalone HTML page."""
    lines = bs.read(rel_html)
    body_i = bs._find(lines, "<body")
    body_close = bs._find(lines, "</body>")
    body = [l for l in lines[body_i + 1:body_close]]
    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()

    # Head pieces: font links + <style> blocks (meta/title are dropped;
    # local stylesheet links other than okina.css are kept and later
    # absolutized to the Pages host by the shared passes).
    head = lines[:body_i]
    fonts = [l for l in head
             if "fonts.googleapis" in l or "fonts.gstatic" in l]
    links = [l.strip() for l in head
             if re.search(r'<link[^>]*rel="stylesheet"', l)
             and "okina.css" not in l
             and "fonts.googleapis" not in l]
    styles = []
    j = 0
    while j < len(head):
        if "<style" in head[j]:
            k = j
            while "</style>" not in head[k]:
                k += 1
            styles.append("\n".join(head[j:k + 1]))
            j = k + 1
        else:
            j += 1

    wrapper_m = re.match(r'\s*<div id="([^"]+)"\s*>\s*$', body[0]) if body else None
    embed_ready = bool(wrapper_m) and body[-1].strip() == "</div>"

    if embed_ready:
        wrapper = wrapper_m.group(1)
        note = ("embed-ready page — its own <div id=\"%s\"> wrapper block is "
                "used verbatim (CSS is trusted to be self-scoped); load-time "
                "init rewritten to survive post-load injection" % wrapper)
        parts = fonts + links + styles + body
        content = "\n".join(parts)
    else:
        wrapper = "ha-%s-embed" % _slug(rel_html)
        css = "\n".join(
            re.sub(r"(?s)^\s*<style[^>]*>|</style>\s*$", "", s) for s in styles
        )
        # The two universal resets used across this codebase must keep zero
        # specificity — same :where() treatment as build_homepage()/support().
        css = css.replace(
            "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }",
            ":where(#%s, #%s *, #%s *::before, #%s *::after) "
            "{ box-sizing: border-box; margin: 0; padding: 0; }"
            % (wrapper, wrapper, wrapper, wrapper),
        )
        css = css.replace(
            "*, *::before, *::after{",
            ":where(#%s *, #%s *::before, #%s *::after){" % (wrapper, wrapper, wrapper),
        )
        css = re.sub(r"(?m)^(\s*)html\s*\{[^}]*\}", "", css)
        css = re.sub(r"(?m)^(\s*)body\s*\{", r"\1#%s {" % wrapper, css, count=1)
        css = "<style>\n" + bs.scope_css_selectors(css, wrapper) + "\n</style>"
        # Standard mobile full-bleed breakout (Squarespace pads the code
        # block's content column on mobile) — same fix as every other page.
        css += (
            "\n<style>\n"
            "@media (max-width:1080px){\n"
            "  #%s{\n"
            "    width: 100vw !important;\n"
            "    max-width: 100vw !important;\n"
            "    margin-left: calc(50%% - 50vw) !important;\n"
            "    margin-right: calc(50%% - 50vw) !important;\n"
            "  }\n"
            "}\n"
            "</style>\n" % wrapper
        )
        note = ("standalone page auto-scoped under #%s by the generic builder "
                "(scripts/squarespace.py); load-time init rewritten to survive "
                "post-load injection" % wrapper)
        content = (
            '<div id="%s">\n' % wrapper
            + "\n".join(fonts + links) + "\n"
            + css + "\n"
            + "\n".join(body) + "\n"
            + "</div>"
        )

    content, patched = patch_onload(content)
    if patched:
        # The helper must precede the content scripts that call it.
        content = re.sub(r'(<div id="[^"]+"\s*>)',
                         lambda m: m.group(1) + "\n" + ONLOAD_HELPER,
                         content, count=1)

    page_name = _slug(rel_html)
    html = (bs.header(page_name, note)
            .replace("scripts/build_squarespace.py", "scripts/squarespace.py")
            + content + "\n")
    html = _normalize_updirs(html, rel_html)
    html = bs.entity_encode(bs.ensure_okina(bs.remap_internal_links(
        bs.absolutize_assets(html))))

    if os.path.basename(rel_html) == "index.html" and os.path.dirname(rel_html):
        out_rel = os.path.join(os.path.dirname(rel_html), "squarespace-inject.html")
    elif os.path.dirname(rel_html):
        out_rel = os.path.join(
            os.path.dirname(rel_html),
            os.path.splitext(os.path.basename(rel_html))[0] + ".squarespace-inject.html")
    else:
        out_rel = os.path.splitext(rel_html)[0] + ".squarespace-inject.html"
    out_path = os.path.join(ROOT, out_rel)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return out_rel


# ---------------------------------------------------------------------------
# Target resolution
# ---------------------------------------------------------------------------

# Hand-authored snippets: no build source, copy as-is.
SNIPPETS = {
    "header-search": "squarespace-header-search.html",
    "footer": "squarespace-footer.html",
    "code-injection": "squarespace-code-injection.html",
    "custom-css": "squarespace-custom-css.css",
    "video-hero": "video-hero/squarespace-inject.html",
}


def builder_targets():
    """name -> squarespace-ready output file, for every build_squarespace page."""
    t = {os.path.splitext(src)[0]: src for src, _, _, _ in bs.MARKER_PAGES}
    t.update({"index": "index.html", "home": "index.html",
              "support": "support.html", "ufsm": "ufsm.html"})
    return t


def generic_sources():
    """Existing generic injects that have a rebuildable source next to them."""
    found = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames
                       if d not in (".git", "node_modules", "squarespace-ready")]
        if "squarespace-inject.html" in filenames and "index.html" in filenames:
            found.append(os.path.relpath(os.path.join(dirpath, "index.html"), ROOT))
    return sorted(found)


def pbcopy(path):
    with open(path, "rb") as f:
        data = f.read()
    subprocess.run(["pbcopy"], input=data, check=True)
    return len(data)


# ---------------------------------------------------------------------------
# --snippet: browser-console paste (see README "Pasting from the browser")
# ---------------------------------------------------------------------------

# One self-contained expression, pasted into the DevTools console (or run by
# Claude via the Chrome MCP) while a Code Block editor is open. It pulls the
# payload straight from GitHub Pages, so the bytes never travel through the
# clipboard or a chat transcript, and size is irrelevant.
#
# Why it is built this way (all four verified live in the 7.1 editor):
#   • Squarespace's code editor is CodeMirror 6 and exposes no EditorView on
#     the DOM, so the document is replaced through the two events CM6 itself
#     listens for: a synthetic Mod-A keydown (its keymap runs selectAll on the
#     STATE, which a DOM Selection cannot do — CM6 only renders the visible
#     lines) followed by a synthetic paste carrying a DataTransfer.
#   • A synthetic paste does register with Squarespace's change tracking: the
#     SAVE button lights up, so the edit is real and will persist.
#   • A real Cmd+V does NOT work — the automation layer's key events do not
#     drive a native clipboard paste.
#   • navigator.clipboard.readText() is a dead end: it needs a focused tab AND
#     a one-time permission grant, and hangs the tab while that prompt is up.
SNIPPET_JS = (
    "await (async () => {"
    "const t = await fetch('%s?t=' + Date.now(), {cache:'no-store'})"
    ".then(r => r.ok ? r.text() : Promise.reject('HTTP ' + r.status));"
    "const c = document.querySelector('.cm-content');"
    "if (!c) throw new Error('No code editor found - open the Code Block editor first');"
    "c.focus();"
    "c.dispatchEvent(new KeyboardEvent('keydown',{key:'a',code:'KeyA',metaKey:true,"
    "keyCode:65,which:65,bubbles:true,cancelable:true}));"
    "const d = new DataTransfer(); d.setData('text/plain', t);"
    "c.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}));"
    "return 'pasted ' + t.length + ' chars';})()"
)


def pages_url(rel_out):
    return bs.ASSET_BASE + rel_out.replace(os.sep, "/")


def check_pages_matches(rel_out):
    """True if GitHub Pages already serves the local bytes. The snippet reads
    from Pages, so an unpushed payload would silently paste the OLD content —
    exactly the stale-paste failure this pipeline exists to prevent."""
    import hashlib
    import urllib.request
    local = hashlib.sha256(open(os.path.join(ROOT, rel_out), "rb").read()).hexdigest()
    try:
        with urllib.request.urlopen(pages_url(rel_out) + "?t=check", timeout=20) as r:
            remote = hashlib.sha256(r.read()).hexdigest()
    except Exception as e:
        return None, "could not reach GitHub Pages (%s)" % e
    return local == remote, None


def emit_snippet(rel_out):
    """Console snippet — NAVIGATION ONLY.

    This used to paste the payload as well, which was wrong: a synthetic paste
    never survives the save (see the NAV_JS comment). It now only opens the
    right Code Block; the paste itself must be a real Cmd+V from the keyboard.
    Prefer `--go`, which does the whole thing."""
    path, title = live_path(rel_out), None
    for t, out in builder_targets().items():
        if os.path.join("squarespace-ready", out) == rel_out:
            title = page_title(t)
            break
    if not (path and title):
        print("No known live path / sidebar title for %s." % rel_out, file=sys.stderr)
        return
    with open(os.path.join(ROOT, rel_out), "rb") as f:
        payload = f.read()
    subprocess.run(["pbcopy"], input=payload, check=True)
    print("%s (%d KB) is on the clipboard." % (rel_out, len(payload) // 1024))
    print("\nRun this in the DevTools console on %s/config/pages to open the"
          " right Code Block:\n" % SITE)
    print(NAV_JS % {"path": path, "title": title})
    print("\nThen in the editor: Cmd+A, then a REAL Cmd+V, then SAVE.")
    print("A scripted paste stages perfectly and SILENTLY FAILS to save.")


def _payload_present(body, live):
    """Is *some* version of this payload on the page? Samples verbatim chunks
    from the payload's interior: a drifted paste still shares long stretches
    with the repo, a page that was never pasted into shares none.

    Deliberately NOT keyed on the generated "PASTE-READY ..." header — pastes
    made before that header existed are still real pastes (the SNAP/Medicaid
    timeline is one), and keying on it reports them as never-published.
    """
    n = len(body)
    if n < 2000:
        return body[:200] in live
    return any(body[int(n * f):int(n * f) + 200] in live
               for f in (0.15, 0.3, 0.45, 0.6, 0.75, 0.9))


# Payloads that are built but deliberately never pasted into Squarespace, with
# the reason. Without this they show up as "absent" drift forever, which reads
# like a backlog when it isn't one.
#
# The three collections are a structural limit, not a gap in this tool: a
# Squarespace blog collection has no block to paste into, and converting one to
# a regular page would break every /blog/<post> URL and the way staff publish.
# Their repo versions render publications.json / news.json for the GitHub Pages
# mirror, which is why they're still maintained.
NOT_PASTE_TARGETS = {
    "squarespace-ready/publications.html":
        "live /publications is a blog collection (blog-basic-grid); Pages mirror only",
    "squarespace-ready/in-the-news.html":
        "live /in-the-news is a blog collection (blog-side-by-side); Pages mirror only",
    "squarespace-ready/blog.html":
        "live /blog is a blog collection (blog-side-by-side); Pages mirror only",
    "squarespace-ready/ufsm.html":
        "embed built (build_ufsm) but never pasted; lives at /ufsm/ on Pages",
}


# Live paths for payloads INTERNAL_LINK_MAP doesn't cover (it only lists the
# pages that are link targets). Generic injects fall out of the rule below.
LIVE_PATH_EXTRA = {
    "squarespace-ready/ufsm.html": "/universal-free-school-meals",
}

_LIVE_CACHE = {}


def live_path(rel_out):
    """The live site path a payload belongs on, or None if we can't know."""
    rel = rel_out.replace(os.sep, "/")
    if rel in LIVE_PATH_EXTRA:
        return LIVE_PATH_EXTRA[rel]
    known = bs.INTERNAL_LINK_MAP.get(os.path.basename(rel_out))
    if known:
        return known
    # Generic injects live at /<dir>, e.g. snap-medicaid-timeline.
    if os.path.basename(rel) == "squarespace-inject.html" and "/" in rel:
        return "/" + rel.rsplit("/", 2)[-2]
    return None


def fetch_live(url):
    """GET a live page, cached per run and paced — Squarespace 429s a fast
    sweep of every page."""
    if url in _LIVE_CACHE:
        return _LIVE_CACHE[url]
    req = urllib.request.Request(url, headers={
        "Cache-Control": "no-cache",
        "User-Agent": "Mozilla/5.0 (squarespace.py --status)"})
    for attempt in (0, 1):
        try:
            with urllib.request.urlopen(req, timeout=25) as r:
                _LIVE_CACHE[url] = r.read().decode("utf-8", "replace")
                return _LIVE_CACHE[url]
        except urllib.error.HTTPError as e:
            if e.code == 429 and attempt == 0:
                time.sleep(20)
                continue
            raise
    return None


def live_state(rel_out):
    """('current'|'stale'|'absent'|None, note). None = could not tell, and the
    caller should carry on rather than treat it as out of date."""
    path = live_path(rel_out)
    if not path:
        return None, "no known live URL for %s" % os.path.basename(rel_out)
    url = SITE + ("" if path == "/" else path)
    try:
        with open(os.path.join(ROOT, rel_out), encoding="utf-8") as f:
            body = f.read().strip()
        live = fetch_live(url)
    except Exception as e:
        return None, "could not check %s (%s)" % (url, e)
    if body in live:
        return "current", url
    if _payload_present(body, live):
        return "stale", url
    return "absent", url


def status(targets=None):
    """For every target with a known live URL, report whether the live page is
    running the payload currently in the repo."""
    rows = []
    known = builder_targets()
    for name in sorted(set(known) - {"home"}):
        rows.append((name, os.path.join("squarespace-ready", known[name])))
    for src in generic_sources():
        d = os.path.dirname(src)
        rows.append((d, os.path.join(d, "squarespace-inject.html")))
    if targets:
        rows = [r for r in rows if r[0] in targets]
    rows = [r for r in rows if os.path.exists(os.path.join(ROOT, r[1]))]

    results = []
    for i, (name, rel) in enumerate(rows):
        url = live_path(rel)
        if url and SITE + url not in _LIVE_CACHE and i:
            time.sleep(1.5)
        state, note = live_state(rel)
        results.append([name, rel, state, note])

    # Several payloads can target one live page (our-mission vs
    # our-mission-light). Only one can be live; the others aren't stale, they
    # are just the variant that isn't in use.
    live_current = {r[3] for r in results if r[2] == "current"}
    for r in results:
        if r[2] in ("stale", "absent") and r[3] in live_current:
            r[2] = "alternate"

    counts = {}
    for name, rel, state, note in results:
        if rel.replace(os.sep, "/") in NOT_PASTE_TARGETS:
            state = "n/a"
            note = NOT_PASTE_TARGETS[rel.replace(os.sep, "/")]
        counts[state] = counts.get(state, 0) + 1
        if state == "current":
            print("  current   %s" % name)
        elif state == "stale":
            print("  STALE     %-22s live page has an older paste" % name)
        elif state == "alternate":
            print("  alternate %-22s not the variant live on %s"
                  % (name, note.replace(SITE, "")))
        elif state == "n/a":
            print("  n/a       %-22s %s" % (name, note))
        elif state == "absent":
            print("  absent    %-22s live page isn't driven by this payload" % name)
        else:
            print("  ?         %-22s %s" % (name, note))
    print("\n%d current, %d stale, %d alternate, %d absent, %d unknown "
          "(+%d not paste targets, of %d)"
          % (counts.get("current", 0), counts.get("stale", 0),
             counts.get("alternate", 0), counts.get("absent", 0),
             counts.get(None, 0), counts.get("n/a", 0), len(results)))
    if counts.get("stale"):
        print("publish with:  python3 scripts/squarespace.py <target> --go")
    return 0


# ---------------------------------------------------------------------------
# --go: one command, ending in the open Code Block editor
# ---------------------------------------------------------------------------
#
#   python3 scripts/squarespace.py our-team --go
#
# rebuild -> commit + push the payload -> wait until GitHub Pages actually
# serves the new bytes -> self-driving console snippet on the clipboard ->
# open Squarespace's Pages panel in your real Chrome. All that is left is to
# paste the snippet in the console and click SAVE.
#
# There is no per-page deep link to open instead: Squarespace 7.1 keeps the URL
# at /config/pages no matter which page is selected, and /config/<slug>
# redirects to Home (both verified live). So the snippet navigates for you — it
# clicks the page in the Pages sidebar by title, presses EDIT, and opens the
# Code Block. Any step it cannot do it names, and you do that one by hand and
# re-run the snippet; every later step still runs.

SITE = "https://hiappleseed.org"
CONFIG_PAGES = SITE + "/config/pages"

# Same paste mechanics as SNIPPET_JS (see the comment there for why CodeMirror
# needs a synthetic Mod-A + paste), preceded by the three navigation steps that
# used to be manual. All four are verified live in the 7.1 editor:
#   • Sidebar rows respond to a synthetic pointer/mouse sequence (a bare
#     .click() on the text node does NOT select the page).
#   • The EDIT button responds to a plain .click().
#   • The Code Block sits in the same-origin #sqs-site-frame preview, and a
#     synthetic dblclick near its top edge opens the editor panel — landing on
#     the top edge avoids the embed's own interactive content.
#   • Pasting content identical to what is live leaves SAVE greyed out; that is
#     "already in sync", not a failure.
# The block editor is CodeMirror 6, and a SYNTHETIC paste does not survive a
# save: it updates CM6's view and even enables SAVE (Squarespace's change
# tracking fires), but Squarespace serialises the block from a model the
# synthetic event never reaches, so the save writes back the OLD content.
# Verified the hard way on taxes-budget — 2,686 correct lines staged, SAVE
# enabled, saved, live page byte-identical to before. Never treat "SAVE lit
# up" as evidence; only the live page is evidence.
#
# What persists is a REAL Cmd+V, driven through System Events. Hence this
# flow: the payload travels on the clipboard (no GitHub Pages round trip, so
# no deploy wait), Chrome is focused deterministically, and the page/block are
# opened by JS run inside the tab.
NAV_JS = r"""
(async () => {
const WANT = "%(path)s";
const sleep = ms => new Promise(r => setTimeout(r, ms));
const until = async (fn, label, ms) => { const t = Date.now(); for (;;) {
  let v = null; try { v = fn(); } catch (e) {}
  if (v) return v;
  if (Date.now() - t > (ms || 45000)) throw new Error("timed out waiting for " + label);
  await sleep(400); } };
const byText = re => Array.from(document.querySelectorAll("button,a,[role=button]"))
  .find(b => re.test((b.textContent || "").trim()));
const framePath = () => { const f = document.querySelector("#sqs-site-frame");
  try { return f ? f.contentWindow.location.pathname : null; } catch (e) { return null; } };

if (framePath() !== WANT) {
  const ex = byText(/^exit$/i); if (ex) { ex.click(); await sleep(3500); }
  // Pick the row by the page it PREVIEWS, never by title: several pages share
  // a sidebar title, and the live issue pages sit in the lower cluster near
  // "Deleted Pages".
  const rows = [];
  for (const e of Array.from(document.querySelectorAll("*"))
      .filter(e => !e.children.length && e.textContent.trim() === "%(title)s")) {
    let n = e;
    for (let i = 0; i < 6 && n && n.getBoundingClientRect().width <= 150; i++) n = n.parentElement;
    if (n && !rows.some(r => r.contains(n) || n.contains(r))) rows.push(n);
  }
  if (!rows.length) throw new Error('no sidebar row titled "%(title)s"');
  let ok = false;
  for (const r of rows) {
    const b = r.getBoundingClientRect();
    const o = {bubbles:true, cancelable:true, view:window,
      clientX:b.left + b.width / 2, clientY:b.top + b.height / 2};
    for (const t of ["pointerdown","mousedown","pointerup","mouseup","click"])
      r.dispatchEvent(new (t[0] === "p" ? PointerEvent : MouseEvent)(t, o));
    await sleep(4500);
    if (framePath() === WANT) { ok = true; break; }
  }
  if (!ok) throw new Error("no row titled \"%(title)s\" previews " + WANT);
}
if (!document.querySelector(".cm-content")) {
  const ed = byText(/^edit$/i); if (ed) { ed.click(); await sleep(4000); }
  const fr = await until(() => document.querySelector("#sqs-site-frame"), "site preview");
  const w = fr.contentWindow;
  const el = await until(() => fr.contentDocument.querySelector(".sqs-block-code"), "code block");
  const n = fr.contentDocument.querySelectorAll(".sqs-block-code").length;
  if (n > 1) throw new Error(n + " code blocks on this page - open the right one by hand");
  if ((el.textContent || "").trim() === "Code")
    throw new Error("this page's Code Block is an empty placeholder - inspect it by hand before pasting");
  // Scroll the block's TOP edge into view. scrollIntoView({block:'center'})
  // is wrong for tall blocks: a 4,400px block lands its top ~1,900px above
  // the viewport and the click point is off-screen.
  w.scrollTo(0, w.scrollY + el.getBoundingClientRect().top - 120);
  await sleep(1800);
  const r = el.getBoundingClientRect();
  const o = {bubbles:true, cancelable:true, view:w,
    clientX:r.left + Math.min(r.width / 2, 400), clientY:r.top + 40, detail:2};
  for (const t of ["mousedown","mouseup","click","mousedown","mouseup","click","dblclick"])
    el.dispatchEvent(new MouseEvent(t, o));
  await until(() => document.querySelector(".cm-content"), "code editor", 25000);
  await sleep(1500);
}
// cm.focus() must be the LAST thing before the paste. If focus sits on the
// preview iframe instead, Cmd+A/Cmd+V goes into the page and the editor panel
// silently closes with SAVE still disabled.
document.querySelector(".cm-content").focus();
return "ready:" + framePath();
})()
"""

VERIFY_JS = r"""
(async () => {
const cm = document.querySelector(".cm-content");
if (!cm) return "ERROR:editor closed - the paste did not land in it";
const sc = document.querySelector(".cm-scroller");
sc.scrollTop = 0; await new Promise(r => setTimeout(r, 900));
const top = Array.from(document.querySelectorAll(".cm-line")).map(l => l.textContent);
const save = Array.from(document.querySelectorAll("button"))
  .find(b => /^save$/i.test((b.textContent || "").trim()));
if (!top.some(l => l.indexOf("%(probe)s") >= 0))
  return "ERROR:pasted text does not look like this page's payload";
if (!save || save.disabled) return "ERROR:SAVE is disabled - nothing was staged";
save.click();
await new Promise(r => setTimeout(r, 8000));
const s2 = Array.from(document.querySelectorAll("button"))
  .find(b => /^save$/i.test((b.textContent || "").trim()));
return "saved:" + (s2 ? s2.disabled : "gone");
})()
"""

ADMIN_MATCH = "/config"


class ChromeJSUnavailable(Exception):
    pass


def _osa(script):
    p = subprocess.run(["osascript", "-"], input=script, text=True,
                       capture_output=True)
    return p.returncode, p.stdout.strip(), p.stderr.strip()


def chrome_js(js, timeout=90):
    """Run JS in Chrome's Squarespace admin tab and return its value.

    Needs Chrome's View > Developer > Allow JavaScript from Apple Events.

    Chrome's `execute javascript` is synchronous: hand it an async IIFE and it
    returns the *Promise*, which serialises to nothing. So async work is kicked
    off into a global and then polled."""
    if js.lstrip().startswith("(async"):
        kick = ("window.__sqs = null; (async () => { try { window.__sqs = "
                "{ok:1, v: await (%s)}; } catch (e) { window.__sqs = "
                "{ok:0, v: String((e && e.message) || e)}; } })(); 'started'"
                % js.strip())
        _chrome_js_raw(kick)
        deadline = time.time() + timeout
        while time.time() < deadline:
            got = _chrome_js_raw("JSON.stringify(window.__sqs)")
            if got and got != "null":
                r = json.loads(got)
                if not r.get("ok"):
                    raise RuntimeError(r.get("v"))
                return r.get("v")
            time.sleep(1)
        raise RuntimeError("timed out after %ss running JS in Chrome" % timeout)
    return _chrome_js_raw(js)


def _chrome_js_raw(js):
    fd = os.path.join(ROOT, ".sqs-exec.js")
    with open(fd, "w", encoding="utf-8") as f:
        f.write(js)
    try:
        # Address the admin tab by URL, never "active tab of front window":
        # the front tab can be anything, and running VERIFY_JS (which clicks
        # SAVE) against the wrong page is not a mistake worth risking.
        rc, out, err = _osa(
            'set js to (read POSIX file "%s" as «class utf8»)\n'
            'tell application "Google Chrome"\n'
            '  repeat with w from 1 to (count of windows)\n'
            '    repeat with t from 1 to (count of tabs of window w)\n'
            '      if (URL of tab t of window w) contains "%s" then\n'
            '        return execute tab t of window w javascript js\n'
            '      end if\n'
            '    end repeat\n'
            '  end repeat\n'
            '  return "NOTAB"\n'
            'end tell' % (fd, ADMIN_MATCH))
    finally:
        os.remove(fd)
    if rc != 0:
        if "Apple Events" in err or "not running" in err:
            raise ChromeJSUnavailable(err)
        raise RuntimeError(err)
    if out == "NOTAB":
        raise RuntimeError("no Squarespace admin tab open in Chrome")
    return out


def focus_admin_tab():
    """Bring the Squarespace admin tab to the front. Returns its URL, or None.
    Find + focus + verify must stay in ONE osascript: any tool call in between
    hands focus back to the caller."""
    rc, out, err = _osa('''
tell application "Google Chrome"
  activate
  set found to false
  repeat with w from 1 to (count of windows)
    repeat with t from 1 to (count of tabs of window w)
      if (URL of tab t of window w) contains "%s" then
        set active tab index of window w to t
        set index of window w to 1
        set found to true
        exit repeat
      end if
    end repeat
    if found then exit repeat
  end repeat
  if not found then return ""
  delay 1.5
  return URL of active tab of front window
end tell''' % ADMIN_MATCH)
    return out or None


def send_real_paste():
    """Cmd+A then a REAL Cmd+V into whatever is focused in Chrome, guarded on
    the front tab so a stray focus change can't paste 100KB somewhere else.
    (It once went into a Google Form.)"""
    rc, out, err = _osa('''
tell application "Google Chrome"
  activate
  delay 1.5
  set u to URL of active tab of front window
end tell
if u does not contain "%s" then
  return "ABORT:" & u
end if
tell application "System Events"
  tell process "Google Chrome"
    keystroke "a" using command down
    delay 0.6
    keystroke "v" using command down
  end tell
end tell
delay 5
return "pasted"''' % ADMIN_MATCH)
    if rc != 0:
        return "ERROR:" + err
    return out


def open_admin():
    subprocess.run(["open", "-a", "Google Chrome", SITE + "/config/pages"],
                   check=False)


def page_title(target):
    """The page's title as it appears in the Pages sidebar. Filename != live
    slug != sidebar title, so publish_squarespace.py's PAGE_TITLES is the
    mapping; anything missing falls back to the live site's own title."""
    stem = os.path.splitext(os.path.basename(target.rstrip("/")))[0]
    try:
        import publish_squarespace as ps
        if stem in ps.PAGE_TITLES:
            return ps.PAGE_TITLES[stem]
    except Exception:
        pass
    try:
        import urllib.request
        with urllib.request.urlopen("%s/%s?format=json" % (SITE, stem), timeout=15) as r:
            return (json.load(r).get("collection") or {}).get("title")
    except Exception:
        return None


def _git(*args):
    return subprocess.run(["git"] + list(args), cwd=ROOT,
                          capture_output=True, text=True)


def ensure_pushed(rel_out, sources):
    """Commit + push the payload (and the source it was built from) so that the
    snippet, which reads from GitHub Pages, cannot paste stale content."""
    paths = [p for p in [rel_out] + list(sources)
             if p and os.path.exists(os.path.join(ROOT, p))]
    _git("add", "--", *paths)
    staged = _git("diff", "--cached", "--name-only").stdout.strip()
    if staged:
        print("committing:")
        for line in staged.splitlines():
            print("  %s" % line)
        c = _git("commit", "-m", "Rebuild Squarespace payload: %s" % rel_out)
        if c.returncode:
            print(c.stdout + c.stderr, file=sys.stderr)
            return False
    ahead = _git("rev-list", "--count", "@{u}..HEAD").stdout.strip()
    if staged or (ahead.isdigit() and int(ahead) > 0):
        print("pushing...")
        p = _git("push")
        if p.returncode:
            print(p.stdout + p.stderr, file=sys.stderr)
            print("push failed — fix that first; the snippet reads from Pages.",
                  file=sys.stderr)
            return False
        print("pushed.")
    dirty = [l for l in _git("status", "--porcelain").stdout.splitlines()
             if not l.startswith("??")]
    if dirty:
        print("note: %d other modified file(s) left uncommitted." % len(dirty))
    return True


def go(target, rel_out, sources, push=True, force=False):
    why = NOT_PASTE_TARGETS.get(rel_out.replace(os.sep, "/"))
    if why and not force:
        print("\n%s is not a Squarespace paste target:\n  %s\n"
              "--force to publish it anyway." % (target, why))
        return 0

    state, note = live_state(rel_out)
    if state == "current" and not force:
        print("\nThe live page is already running this payload:\n  %s\n"
              "Nothing to publish. --force to publish it anyway." % note)
        return 0
    if state == "absent":
        print("note: none of this payload is on %s — that page may not be "
              "driven by a Code Block." % note)
    elif state is None:
        print("live check: %s — continuing." % note)

    # Committed for provenance, but nothing waits on the deploy: the payload
    # reaches Squarespace on the clipboard, not via GitHub Pages.
    if push:
        ensure_pushed(rel_out, sources)

    path = live_path(rel_out)
    title = page_title(target)
    if not (path and title):
        print("Don't know the live path/sidebar title for %s — add it to "
              "LIVE_PATH_EXTRA / PAGE_TITLES." % target, file=sys.stderr)
        return 1

    with open(os.path.join(ROOT, rel_out), "rb") as f:
        payload = f.read()
    subprocess.run(["pbcopy"], input=payload, check=True)
    print("payload : %s (%d KB) on the clipboard" % (rel_out, len(payload) // 1024))
    print("page    : %s  ->  %s" % (title, path))

    url = focus_admin_tab()
    if not url:
        open_admin()
        print("\nOpened the Squarespace Pages panel — log in if needed, then "
              "re-run this command.")
        return 1

    probe = "PASTE-READY" if b"PASTE-READY" in payload[:400] else title[:12]
    try:
        res = chrome_js(NAV_JS % {"path": path, "title": title})
    except ChromeJSUnavailable:
        print("""
Chrome won't let me script the page, so I can't open the block for you.
Turn it on once: Chrome menu > View > Developer > Allow JavaScript from Apple
Events. Then re-run and this whole command is automatic.

For now, the payload is on the clipboard and the admin tab is focused:
  1. Click the page in the sidebar, then EDIT.
  2. Double-click the Code Block (its editor opens on the right).
  3. Cmd+A, then Cmd+V  <- a REAL Cmd+V; a scripted paste does NOT save.
  4. Click SAVE.
Then check it landed:  python3 scripts/squarespace.py %s --status""" % target)
        return 1
    if not res.startswith("ready:"):
        print("could not open the Code Block: %s" % res, file=sys.stderr)
        return 1

    out = send_real_paste()
    if not out.startswith("pasted"):
        print("paste aborted: %s" % out, file=sys.stderr)
        return 1

    res = chrome_js(VERIFY_JS % {"probe": probe})
    if not res.startswith("saved:"):
        print("%s" % res, file=sys.stderr)
        return 1

    # The only evidence that counts.
    state, note = live_state(rel_out)
    if state == "current":
        print("\nPublished and verified live: %s" % note)
        return 0
    print("\nSAVE was clicked but the live page does not match yet (%s).\n"
          "Re-check in a moment:  python3 scripts/squarespace.py %s --status"
          % (state, target), file=sys.stderr)
    return 1




def copy_and_report(rel_out):
    size = pbcopy(os.path.join(ROOT, rel_out))
    print("\n%s (%d KB) is on the clipboard." % (rel_out, round(size / 1024)))
    print("Squarespace: Edit page > add/select Code Block > select all > paste"
          " > Display Source OFF > Save.")


def list_targets():
    print("Built by build_squarespace.py (squarespace-ready/):")
    for name in sorted(set(builder_targets()) - {"home"}):
        print("  %s" % name)
    print("Generic injects (rebuilt from <dir>/index.html):")
    for src in generic_sources():
        print("  %s" % os.path.dirname(src))
    print("Hand-authored snippets (copied as-is):")
    for name, path in sorted(SNIPPETS.items()):
        print("  %-14s -> %s" % (name, path))
    print("Anything else: pass a directory with index.html, or any .html path.")


def main(argv):
    snippet = "--snippet" in argv
    go_mode = "--go" in argv
    status_mode = "--status" in argv
    force = "--force" in argv
    push = "--no-push" not in argv
    copy = "--no-copy" not in argv and not snippet and not go_mode
    argv = [a for a in argv if a not in ("--no-copy", "--snippet", "--go",
                                         "--no-push", "--status", "--force")]

    if status_mode and (not argv or argv[0] == "--all"):
        bs.main()
        for src in generic_sources():
            build_generic(src)
        print("live pages vs the payloads in this repo:\n")
        return status()

    if not argv:
        list_targets()
        return 0

    if argv[0] == "--all":
        bs.main()
        for src in generic_sources():
            print("regenerated %s" % build_generic(src))
        return 0

    target = argv[0].rstrip("/")
    sources = []

    known = builder_targets()
    stem = os.path.splitext(target)[0]
    if stem in known:
        bs.main()
        out = os.path.join("squarespace-ready", known[stem])
        if os.path.exists(os.path.join(ROOT, stem + ".html")):
            sources.append(stem + ".html")
    elif target in SNIPPETS:
        out = SNIPPETS[target]
    else:
        # Generic: directory with index.html, or a direct .html path.
        if os.path.isdir(os.path.join(ROOT, target)):
            rel = os.path.join(target, "index.html")
        else:
            rel = target if target.endswith(".html") else target + ".html"
        if not os.path.exists(os.path.join(ROOT, rel)):
            print("No such target: %s (run with no arguments to list)" % target,
                  file=sys.stderr)
            return 1
        out = build_generic(rel)
        sources.append(rel)
        print("built %s" % out)

    if status_mode:
        return status([target])
    if go_mode:
        return go(target, out, sources, push=push, force=force)
    if snippet:
        emit_snippet(out)
    elif copy:
        copy_and_report(out)
    else:
        print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
